FROM registry.access.redhat.com/ubi8/ubi-minimal
WORKDIR /work/
COPY target/*-runner /work/application
RUN chmod 775 /work

RUN mkdir /opt/kafka-exporter;
ADD src/main/docker/kafka_exporter_run_native.sh /opt/kafka-exporter/kafka_exporter_run.sh
RUN chmod +x /opt/kafka-exporter/kafka_exporter_run.sh
